### PR TITLE
Update test dependencies

### PR DESCRIPTION
**Pull request by nikolas**
Mainly for the latest pagetree

### CODE REVIEW

**Comment by nikolas** [comment]
This is failing because pagetree 1.0.5 isn't on https://pypi.python.org/pypi/django-pagetree. Is @thraxil the only one who updates django-pagetree there, or should I be able to upload there too?

**Comment by sdreher** [comment]
I believe only @thraxil is uploading to pypi at the moment. No reason for you not to do an upload imho.

**Comment by nikolas** [comment]
I see. I think @coati-00 was asking about this as well. Either way works for me, but in any case we should get pagetree 1.0.5 up there so we can test pageblocks against it.

**Comment by coati-00** [comment]
Yeah @nikolas  you should be able to

**Pull request merged**
